POST http://localhost:3000/api/send-private
Content-Type: application/json

{
    "apiKey": "rahasia",
    "number": "6285281411550",
    "message": "Halo, ini adalah pesan pribadi."
}

###

POST http://localhost:3000/api/send-group
Content-Type: application/json

{
    "apiKey": "rahasia",
    "groupId": "120363403933067028",
    "message": "Halo, ini adalah pesan grup."
}

###
POST http://10.0.108.248:3000/api/send-private
Content-Type: application/json

{
    "apiKey": "tes123",
    "number": "6285281411550",
    "message": "Halo, ini adalah pesan pribadi."
}


###

POST http://10.0.108.248:3000/api/send-group
Content-Type: application/json

{
    "apiKey": "tes123",
    "groupId": "120363169750068863",
    "message": "Halo, ini adalah pesan grup."
}


